const PDFDocument = require('pdfkit');
const path = require('path');
const fs = require('fs');
const { v4: uuidv4 } = require('uuid');

const outputDir = path.join(process.cwd(), 'uploads', 'documents');
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

const htmlToPdfContent = (html) => {
  const cleaned = html
    .replace(/<style[^>]*>[\s\S]*?<\/style>/gi, '')
    .replace(/<script[^>]*>[\s\S]*?<\/script>/gi, '')
    .replace(/<br\s*\/?>/gi, '\n')
    .replace(/<\/p>/gi, '\n\n')
    .replace(/<\/h1>/gi, '\n\n')
    .replace(/<\/h2>/gi, '\n\n')
    .replace(/<\/h3>/gi, '\n\n')
    .replace(/<\/li>/gi, '\n')
    .replace(/<\/tr>/gi, '\n')
    .replace(/<\/td>/gi, '\t')
    .replace(/<[^>]+>/g, '')
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/\n{3,}/g, '\n\n')
    .trim();

  const lines = cleaned.split('\n').map((l) => l.trim()).filter(Boolean);
  return lines;
};

async function generateDocumentPdf(title, htmlContent) {
  const filename = `${uuidv4()}.pdf`;
  const filepath = path.join(outputDir, filename);
  const lines = htmlToPdfContent(htmlContent);

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: 'A4',
      margins: { top: 60, bottom: 60, left: 60, right: 60 },
      info: { Title: title },
    });

    const stream = fs.createWriteStream(filepath);
    doc.pipe(stream);

    doc.font('Helvetica-Bold').fontSize(22).text(title, { align: 'center' });
    doc.moveDown(1.5);

    doc.font('Helvetica').fontSize(11);

    for (const line of lines) {
      if (line.startsWith('Subject:')) {
        doc.moveDown(0.5);
        doc.font('Helvetica-Bold').fontSize(11).text(line);
        doc.font('Helvetica').moveDown(0.5);
      } else if (line.startsWith('QIST Market') && !line.startsWith('QIST Market.')) {
        doc.font('Helvetica-Bold').fontSize(11).text(line);
        doc.font('Helvetica');
      } else {
        doc.text(line, { align: 'justify' });
      }
      doc.moveDown(0.3);
    }

    doc.moveDown(2);
    doc.fontSize(9).fillColor('#888').text('— Generated by QIST Market HR Portal —', { align: 'center' });

    doc.end();

    stream.on('finish', () => resolve({ filename, filepath, url: `/uploads/documents/${filename}` }));
    stream.on('error', reject);
  });
}

async function generateDocumentVersion(title, htmlContent, version, prevUrl) {
  const pdf = await generateDocumentPdf(`${title} (v${version})`, htmlContent);
  const historyDir = path.join(outputDir, 'history');
  if (!fs.existsSync(historyDir)) fs.mkdirSync(historyDir, { recursive: true });

  const historyEntry = {
    version,
    title,
    url: pdf.url,
    filepath: pdf.filepath,
    createdAt: new Date().toISOString(),
  };

  const historyFilename = `history-${uuidv4()}.json`;
  const historyFilepath = path.join(historyDir, historyFilename);
  fs.writeFileSync(historyFilepath, JSON.stringify(historyEntry, null, 2));

  return { pdf, history: historyEntry };
}

module.exports = { generateDocumentPdf, outputDir };
